### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by nickyat** [panstromek/quasar-ide-helper#13]
I will be grateful for the hint why helper does not work after add and generate command.
use last quasar  v1.b.16
Try WebStorm 2019.1, IntelliJ 2019.1 without success.

![nodocs](https://user-images.githubusercontent.com/8930171/55996971-c1b7c300-5cc1-11e9-89eb-53aaea8125db.gif)
i don't see any  docs like here 
![original](https://user-images.githubusercontent.com/8930171/55997530-7ef6ea80-5cc3-11e9-9e4b-262f5e529b1b.gif)

ex: no docs after input icon props (but popup with Ctrl-Q ):
![nodocs2](https://user-images.githubusercontent.com/8930171/55997435-2889ac00-5cc3-11e9-8074-c7f23f618ee8.gif)

**Comment by panstromek** [comment]
I don't really understand, what is not working? I see that you have no "unknown tag" errors there and attributes are shown in the autocomplete list, that is a sign it works as expected.

As for the docs and `ctrl+q` inconsistencies, those are problems of the Vue plugin and intellij platform, I can't control that. Eg. `ctrl+q` doesn't work when you are on tag, but it works when you `ctrl+space` instead and then `ctrl+q` in the completion list. Attribute docs shows only if you do `ctrl+q`, not automatically - there is `ctrl+space` and `ctrl+q` pressed multiple times in that gif from article.

I am closing this because these are problems to report on Vue IntelliJ plugin. Helper only generates files to index, it is not a plugin and does not control these things.
