### ISSUE TITLE
[Question] is this helper works with quasar vite-plugin project?

### ISSUE THREAD

**Issue by alphaelf** [panstromek/quasar-ide-helper#27]

**Comment by panstromek** [comment]
I am not sure, I haven't tried that, but I don't think using this helper is worthwile anymore. WebStorm already supports majority of the features natively.

**Comment by BenceSzalai** [comment]
It does not work, because it tries to do some webpack specific things here:
https://github.com/panstromek/quasar-ide-helper/blob/master/src/generators/fake-webpack-config.js#L39

It could be used if it had an option to disable the webpack related file generation.

Simply commenting out this line makes it work with Vite:
https://github.com/panstromek/quasar-ide-helper/blob/master/src/index.js#L24

Let me know if PR is welcome for Vite mode option!

**Comment by panstromek** [comment]
PR is welcome, sure 😉 but I'm not sure if it's worth investing more time in it. As I said, I am not sure if it's even worth using the helper at this point.

I'm genuinely curious if you still get something out if it. Is there a specific feature you are looking for that isn't in the WebStorm natively already?

**Comment by BenceSzalai** [comment]
Alright, that's an interesting proposition. TBH I've just migrated a project to Quasar v2 and Vite from Quasar v1 and Webpack few days ago, so I don't have much experience with it so far. But generally speaking when working with the project it is not really visible what IDE features are coming from this helper and which ones are native, so you could be right without me seeing: it may not even be needed any more. 

I'd just assumed it was useful. I've been just using it for the sake of getting the max out of the IDE, not because it has been addressing some specific needs of mine, even though there may have been some when I started using, but i cannot remember any more.

I guess some more in depth analysis would be needed to answer the question. On the other hand: what changes do you reckon was made into JetBrains IDE's that were missing before and made this extension needed in the first place?

**Comment by BenceSzalai** [comment]
Did it anyway meanwhile, it was not a big deal: https://github.com/panstromek/quasar-ide-helper/pull/28

**Comment by panstromek** [comment]
When I made the extension, WebStorm couldn't provide autocomplete for almost everything from quasar because it's built in a custom way that the IDE can't analyze. Since then, WebStorm introduced a schema in which libraries can describe components and properties. Quasar now generates it, so most autocomplete should work fine out of the box.

They also improved Vue support in general. As far as I know, the only missing thing today is that enum-like properies are not nicely autocompleted, see https://github.com/panstromek/quasar-ide-helper/issues/17.

You can try to uninstall the helper and delete all its files, you'll see if you notice something. (btw. I myself don't use the helper anymore).

**Comment by panstromek** [comment]
> Did it anyway meanwhile, it was not a big deal: #28

Nice!

**Comment by panstromek** [comment]
fixed in https://github.com/panstromek/quasar-ide-helper/pull/28

**Comment by BenceSzalai** [comment]
Oh, by the way, I mixed [Quasar Vite Plugin](https://quasar.dev/start/vite-plugin) project with [Quasar CLI with Vite](https://quasar.dev/start/quasar-cli), so I'm not sure if this works with the former, but it for sure works with the later after the fix. Sorry for the mess.
