### ISSUE TITLE
[autocomplete] - @type autocomplete add `_` prop

### ISSUE THREAD

**Issue by DaedalusDev** [panstromek/quasar-ide-helper#7]
First of all, thanks for your great job

# Steps to reproduce
Insert a supported quasar tag. Type a prop with specified @type.

# What is expected?
The props should append

# What is actually happening?
Autocomplete append the following :
```html
<q-ajax-bar position="bottom" _="" />
```

**Comment by panstromek** [comment]
yea, the `_=""` is intentional... Maybe I should remove this feature alltogether, I don't really know.

The problem is: IntelliJ doesn't understand types when autocompleting attributes. Which is unfortunate especially for enum types like `anchor` and `self` (or the `position` you refer to) because those have only few options like `"bottom left" "top start" ...` .

I wanted to give some support for those so you don't need to remember them (I always have to look them up) and since completion from jsdoc typings doesn't work for attributes, the only solution I found working was to "fake it" with hardcoded prop name, like this:

```js
    'position="top"': {
      type: String,
    },
```
now the problem with this is that IDEA will autocomplete but also appends `=""` at the end because it assumes you will want to fill in a value: 

```vue
<q-ajax-bar position="bottom"="" />
```
that is invalid syntax, so I ended up using the workaround with ` _` so that after idea appends `=""`, result is at least somehow valid HTML. Like this:

```js
    'position="top" _': {
      type: String,
    },
```
Since there is no way to stop IDEA from appending `=""` for now, I don't really know how to resolve this. What do you think I should do? 

 1. Remove this feature altogether - In the end you can see the enum options if you press `ctrl+q` inside quotes or if you `ctrl+b` on the attribute....
 2. Leave out the ` _` bit, so IDEA will append invalid `=""`, but you will have to delete less garbage afterwards.
 3. Leave it like it is now...

We can make this work if [this](https://youtrack.jetbrains.com/issue/WEB-34383) issue gets resolved, so go upvote it if you can ;)

**Comment by DaedalusDev** [comment]
Ho ! Well ! Haven't saw sorry !

Unfortunaly, i don't know the best way... 

I'm agree with you and i'v upvote for the `Boolean type better support` on YouTrack.
Hope they will accept this feature request ! :crossed_fingers: 

Thanks again for your great job !
